version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # ارجاع به گواهی‌ها
    depends_on:
      - php
    networks:
      - laravel_network

  mysql:
    image: mysql:5.7
    container_name: mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prod_password
      MYSQL_DATABASE: production_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
