version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app-vivify
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: mysql-vivify
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vivify
      MYSQL_DATABASE: vivify_db
      MYSQL_USER: vivify_user
      MYSQL_PASSWORD: vivify_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: redis-vivify
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

  nginx:
    image: nginx:1.27
    container_name: nginx-vivify
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # ارجاع به گواهی‌ها
      - ./:/var/www
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
