  mysql:
    image: mysql:5.7
    container_name: mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prod_password
      MYSQL_DATABASE: production_db
      MYSQL_USER: custom_user  # نام کاربری دلخواه
      MYSQL_PASSWORD: user_password  # رمز عبور دلخواه
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
